# Generated by Django 3.2.12 on 2022-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_auto_20220826_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='altkategoriler',
            field=models.ManyToManyField(blank=True, to='urunler.AltKategori'),
        ),
    ]
