# Generated by Django 3.2.12 on 2022-08-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_auto_20220826_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnAlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='enalt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.enalt'),
        ),
    ]
