# Generated by Django 3.2.12 on 2022-08-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_auto_20220826_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='altkategori',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori'),
        ),
    ]
